# Generated by Django 5.2.5 on 2025-09-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_description_skill_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
