# Generated by Django 5.2.5 on 2025-09-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_description3_skill_description4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description4',
            field=models.TextField(blank=True, default=''),
        ),
    ]
