# Generated by Django 5.2.5 on 2025-09-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_skill_description3_alter_skill_description4'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description4',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.skillcategory'),
        ),
    ]
