# Generated by Django 5.2.5 on 2025-09-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='description1',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description2',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='description4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
