# Generated by Django 5.2.5 on 2025-09-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('category',)},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
    ]
