# Generated by Django 5.2.5 on 2025-09-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
