# Generated by Django 5.2.5 on 2025-09-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_skill_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='read',
        ),
    ]
